### PR TITLE
Implement Starknet logic

### PR DESCRIPTION
**Pull request by kariy**

### CODE REVIEW

**Comment by kariy** [comment]
There are still some fixes need to be done on the state part but it wouldn't incur huge changes. So, I'm opening it for review now.

**Review by tarrencev — APPROVED** [review]
Really incredible progress! This looks great. Let's merge and add archive, rpc etc as follow up PRs

**Comment by kariy** [comment]
Doing some clean ups and after that I'll merge.

**Comment by kariy** [comment]
LGTM 🔥

**Pull request merged**
