### PR TITLE
Implement `starknet_addDeclareTransaction`

### PR DESCRIPTION
**Pull request by kariy**
- Supporting declare v2 transaction only

### CODE REVIEW

**Comment by kariy** [comment]
Converting between all the different contract class types is such a pain in the ass, honestly.

**Comment by tarrencev** [comment]
> Converting between all the different contract class types is such a pain in the ass, honestly.

Seriously. It should get better soon though

**Comment by kariy** [comment]
I had a stroke while doing this

**Comment by kariy** [comment]
Removed `declare` v1 transaction as it is already deprecated.

**Review by tarrencev — APPROVED** [review]

**Pull request merged**
